# -----------------------
#
# Run a full build-and-test from the git repo
# using uv to install all dependencies.
#
# This is the 'full' test suite.
#
# -----------------------

name: Build and test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS
          - Ubuntu
        python-version:
          - "3.10"
          - "3.11"
    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Package list
      run: uv pip list

    - name: Run test suite
      run: uv run -m pytest -ra --color yes --cov hveto --pyargs hveto.tests --junitxml=pytest.xml

    - name: Sanity check entry points
      run: |
        uv run -m coverage run --append --source hveto -m hveto --help
        uv run -m coverage run --append --source hveto -m hveto.cli.cache_events --help
        uv run -m coverage run --append --source hveto -m hveto.cli.trace --help

    - name: Coverage report
      run: uv run -m coverage report --show-missing

    - name: Prepare codecov upload
      run: uv run -m coverage xml

    - name: Publish coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.xml
        flags: ${{ runner.os }},python${{ matrix.python-version }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: pytest-${{ matrix.os }}-${{ matrix.python-version }}
        path: pytest.xml
